name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID to build'
        required: true
        default: 'latest_commit_id'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_id }}  # Checkout specific commit ID

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker image build -t binupeter/hello-flask:${{ github.event.inputs.commit_id }} .
        
      - name: Push Docker image
        run: |
          docker image push binupeter/hello-flask:${{ github.event.inputs.commit_id }}


